Translate mythbusters.
salmer/CppDeveloperRoadmap pull request #15
Opened 2021-10-31 17:09 UTC by SD57

Maybe "Witnesses of Dead C++"?
The rest feels OK.

2021-10-31 17:10 UTC, SD57 commented
@salmer @DmitrievDmitriyA review pls.

2021-11-01 17:04 UTC, salmer commented
> Maybe "Witnesses of Dead C++"? The rest feels OK.

I'd say the original name describes an article's intention better. The article contains a collection of biases about C++ not only related to the "death" of the language.

2021-11-01 17:06 UTC, SD57 commented
> > Maybe "Witnesses of Dead C++"? The rest feels OK.
> 
> I'd say the original name describes an article's intention better. The article contains a collection of biases about C++ not only related to the "death" of the language.

I meant the first paragraph, not the title.

2021-11-01 17:11 UTC, salmer requested changes

2021-11-01 17:11 UTC, salmer commented on English/Mythbusters.md
> +## Reals programmers learn C++ using Linux/Vim/gcc
Real programmers? Typo issue in Real"s"?

2021-11-01 17:11 UTC, salmer commented on English/Mythbusters.md
> +This is another urban legend from the Old Guard that had stopped writing C++ before C++11 or those who superficially learned it in university disregarding the latest standards. Modern C++ contains a
Old Guard in quotes as it's done before?

2021-11-01 17:11 UTC, salmer commented on English/Mythbusters.md
> +## Reals programmers learn C++ using Linux/Vim/gcc
Real programmers? Typo issue in Real"s"?

2021-11-01 17:12 UTC, salmer commented
2 comments are left only, plz check. In general, the article looks perfect!

2021-11-01 17:15 UTC, SD57 commented
> 2 comments are left only, plz check. In general, the article looks perfect!

I agree with the changes. Could you please apply them? I'm on the phone right now - not sure when  I'll get to the laptop.

2021-11-02 07:38 UTC, merged