Translated SelfIdentification.md
salmer/CppDeveloperRoadmap pull request #18
Opened 2021-11-02 21:19 UTC by DmitrievDmitriyA

2021-11-02 21:53 UTC, DmitrievDmitriyA commented
@salmer @SD57 у меня есть ощущение, что "romanticized image" надо как-то по-другому перевести. Есть идеи? Или и так норм?

2021-11-02 22:03 UTC, SD57 commented
> @salmer @SD57 у меня есть ощущение, что "romanticized image" надо как-то по-другому перевести. Есть идеи? Или и так норм?

Maybe "idealized image"?

2021-11-03 07:03 UTC, salmer requested changes

2021-11-03 07:03 UTC, salmer commented on English/SelfIdentification.md
> +C ++ is rich in ideas and coding approaches. Therefore, it is recommended to start learning the language with a clean head. Understand its ideas. This will help you to use the language effectively in
C ++ "space" between C and ++

2021-11-03 07:04 UTC, salmer commented
> @salmer @SD57 у меня есть ощущение, что "romanticized image" надо как-то по-другому перевести. Есть идеи? Или и так норм?

"fictional image"?

2021-11-03 08:21 UTC, DmitrievDmitriyA commented
@salmer @SD57 в моём сердечке победил "idealized image"

2021-11-03 16:39 UTC, salmer approved these changes

2021-11-03 16:39 UTC, merged