Added information about unit testing book in Books/Middle.md
salmer/CppDeveloperRoadmap pull request #81
Opened 2023-03-17 19:25 UTC by albrt-dev

2023-03-19 17:18 UTC, salmer requested changes

2023-03-19 17:18 UTC, salmer commented on Russian/Books/Middle.md
> +   В книге подробно рассматриваются рекомендации, паттерны и антипаттерны, встречающиеся в области юнит-тестирования. После чтения этой книги вы будете знать все необходимое для того, чтобы стать экс
Hi @albrt-dev. Please fix the repetitive part: "проектов — проектов,".

2023-03-19 17:18 UTC, salmer commented on English/Books/Middle.md
> +   The book details the recommendations, patterns, and anti-patterns found in the field of unit testing. After reading this book, you will know everything you need to be an expert at creating success
The Google translate is not acceptable :)

I reworked it in the following way, please update it:

"The book provides a detailed overview of recommendations, patterns, and anti-patterns commonly encountered in the field of unit testing. After reading this book, you will know everything you need to become an expert in creating successful projects that are easily scalable and maintainable thanks to good tests."

2023-03-20 16:26 UTC, albrt-dev commented on Russian/Books/Middle.md
> +   В книге подробно рассматриваются рекомендации, паттерны и антипаттерны, встречающиеся в области юнит-тестирования. После чтения этой книги вы будете знать все необходимое для того, чтобы стать экс
Updated.

2023-03-21 06:43 UTC, salmer commented
@albrt-dev looks good, thank you for your contribution

2023-03-21 06:44 UTC, salmer approved these changes

2023-03-21 06:44 UTC, merged